Controllers/CourseController.cs
using LearningSystem.Models;
using LearningSystem.Repository;
using LearningSystem.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace LearningSystem.Controllers
{
    public class CourseController : Controller
    {

        ICourseRepository courseRepository;
        IDepartmentRepository departmentRepository;
        public CourseController(ICourseRepository courseRepository,IDepartmentRepository departmentRepository)
        {
            this.courseRepository = courseRepository;
            this.departmentRepository = departmentRepository;
        }

        public IActionResult Index()
        {
            List<Course> instructorsModel = courseRepository.GetAll();
            return View(instructorsModel);
        }
        public IActionResult New()
        {
            CourseDeptVM vm = new CourseDeptVM();
            List<Department> deptList =departmentRepository.GetAll();
            vm.Departments = deptList;
            return View(vm);
        }

        [HttpPost]
        public IActionResult New(Course Crs)
        {


            if (ModelState.IsValid == true)
            {
                try
                {
                    courseRepository.Insert(Crs);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Dept_ID", "Select Department");
                }

            }

            CourseDeptVM vm = new CourseDeptVM();
            List<Department> deptList = departmentRepository.GetAll();
            vm.Departments = deptList;
            vm.Id = Crs.Id;
            vm.Name = Crs.Name;
            vm.Degree = Crs.Degree;
            vm.minDegree = Crs.minDegree;
            vm.Dept_Id = Crs.Dept_Id;
            return View(vm);
        }

        public IActionResult Edit(int id)
        {
            Course Crs = courseRepository.GetById(id);
            CourseDeptVM vm = new CourseDeptVM();
            List<Department> deptList = departmentRepository.GetAll();
            vm.Departments = deptList;
            vm.Id = Crs.Id;
            vm.Name = Crs.Name;
            vm.Degree = Crs.Degree;
            vm.minDegree = Crs.minDegree;
            vm.Dept_Id = Crs.Dept_Id;
            return View(vm);
        }

        [HttpPost]
        public IActionResult Edit([FromRoute] int id, Course Crs)
        {
            if (ModelState.IsValid == true)
            {
                try
                {
                    courseRepository.Update(Crs);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Dept_ID", "Select Department");
                }
            }
            CourseDeptVM vm = new CourseDeptVM();
            List<Department> deptList = departmentRepository.GetAll();
            vm.Departments = deptList;
            vm.Id = Crs.Id;
            vm.Name = Crs.Name;
            vm.Degree = Crs.Degree;
            vm.minDegree = Crs.minDegree;
            vm.Dept_Id = Crs.Dept_Id;
            return View(vm);
        }


        public IActionResult DeleteCourse(int id)
        {
            courseRepository.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult CheckminDegree(int minDegree, int Degree)
        {
            if (minDegree < Degree)
                return Json(true);
            else
                return Json(false);
        }

        public IActionResult CheckName(string Name, int Id)
        {
            Course course = courseRepository.GetByName(Name);
            //Course courseReq = courseRepository.GetById(Id);

           if (course == null /*|| (course != null && course.Id == courseReq.Id)*/)
            {
                return Json(true);
            }
            return Json(false);

        }

    }
}

Controllers/InstractorController.cs
using LearningSystem.Models;
using LearningSystem.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language.Intermediate;
using Microsoft.EntityFrameworkCore;
using System.IO;

namespace LearningSystem.Controllers
{
    public class InstractorController : Controller
    {
        ITIEntity context;
        public InstractorController(ITIEntity context)
        {
            this.context = context;

        }
        public IActionResult Index()
        {
            List<Instructor> instructorsModel = context.Instructors.Include(i => i.Course).Include(i => i.Department).ToList();
            return View(instructorsModel);
        }
        public IActionResult New()
        {
            InstractorDeptCourseVM vm = new InstractorDeptCourseVM();
            List<Department> deptList = context.Departments.ToList();
            List<Course> courseList = context.Courses.ToList();
            vm.Courses = courseList;
            vm.Departments = deptList;
            return View(vm);
        }


        [HttpPost]
        public IActionResult New ( Instructor ins)
        {
            if (ins.Name!= null)
            {
                //if (ins.Image != null && ins.Image.Length > 0)
                //{

                //    var fileName = Path.GetFileName(ins.Image);
                //    var path = Path.Combine(Server.MapPath("~/uploads"), fileName);
                //    ins.Image.SaveAs(path);
                //}

                context.Instructors.Add(ins);
                context.SaveChanges();
                return RedirectToAction("Index");

            }
            InstractorDeptCourseVM vm = new InstractorDeptCourseVM();
            List<Department> deptList = context.Departments.ToList();
            List<Course> courseList = context.Courses.ToList();
            vm.id = ins.Id;
            vm.Name = ins.Name;
            vm.Address = ins.Address;
            vm.Image = ins.Image;
            vm.Salary = ins.Salary;
            vm.Dept_Id = ins.Dept_Id;
            vm.Crs_Id = ins.Crs_Id;
            vm.Courses = courseList;
            vm.Departments = deptList;
            return View(vm);
        }


        public IActionResult Edit(int id)
        {
            Instructor ins = context.Instructors.FirstOrDefault(ins=> ins.Id == id);
            InstractorDeptCourseVM vm = new InstractorDeptCourseVM();
            List<Department> deptList = context.Departments.ToList();
            List<Course> courseList = context.Courses.ToList();
            vm.id = ins.Id;
            vm.Name = ins.Name;
            vm.Address = ins.Address;
            vm.Image = ins.Image;
            vm.Salary = ins.Salary;
            vm.Dept_Id = ins.Dept_Id;
            vm.Crs_Id = ins.Crs_Id;
            vm.Courses = courseList;
            vm.Departments = deptList;
            return View(vm);
        }

        [HttpPost]
        public IActionResult Edit([FromRoute] int id, Instructor ins)
        {
            if (ins.Name != null)
            {
               
                context.Update(ins);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            InstractorDeptCourseVM vm = new InstractorDeptCourseVM();
            List<Department> deptList = context.Departments.ToList();
            List<Course> courseList = context.Courses.ToList();
            vm.id = ins.Id;
            vm.Name = ins.Name;
            vm.Address = ins.Address;
            vm.Image = ins.Image;
            vm.Salary = ins.Salary;
            vm.Dept_Id = ins.Dept_Id;
            vm.Crs_Id = ins.Crs_Id;
            vm.Courses = courseList;
            vm.Departments = deptList;
            return View(vm);
        }
        public IActionResult Details(int id )
        {
            Instructor instructorModel = context.Instructors.FirstOrDefault(ins=>ins.Id==id);

            return View(instructorModel);
        }


        public IActionResult DetailsPartial(int id)
        {
            Instructor instructorModel = context.Instructors.FirstOrDefault(ins => ins.Id == id);

            return PartialView("_DetailsPartial", instructorModel);
        }

        public IActionResult GetCrsByDeptID(int deptID)
        {
            List<Course> courses = context.Courses.Where(c =>c.Dept_Id == deptID).ToList();
            return Json(courses);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LearningSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LearningSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LearningSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instractor" asp-action="Index">Instructor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LearningSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_NavPartail.cshtml
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
        <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#portfolio">Portfolio</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#about">About</a></li>
                <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#contact">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>